"""initial_schema

Revision ID: 7401f23daf39
Revises: 
Create Date: 2026-03-11 18:37:15.562746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7401f23daf39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_size', sa.Float(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('reporting_unit', sa.String(), nullable=True),
    sa.Column('detected_unit', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('credit_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('geographic_risk', sa.String(), nullable=True),
    sa.Column('business_stage', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('loan_type', sa.String(), nullable=True),
    sa.Column('years_in_operation', sa.Integer(), nullable=True),
    sa.Column('requested_amount', sa.Float(), nullable=True),
    sa.Column('currency_scale', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_band', sa.String(), nullable=True),
    sa.Column('policy_limit', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_analyses_document_id'), 'credit_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_credit_analyses_id'), 'credit_analyses', ['id'], unique=False)
    op.create_table('extracted_financials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.String(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cogs', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('st_debt', sa.Float(), nullable=True),
    sa.Column('lt_debt', sa.Float(), nullable=True),
    sa.Column('operating_cf', sa.Float(), nullable=True),
    sa.Column('capex', sa.Float(), nullable=True),
    sa.Column('da', sa.Float(), nullable=True),
    sa.Column('selected_year', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_financials_document_id'), 'extracted_financials', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_financials_id'), 'extracted_financials', ['id'], unique=False)
    op.create_table('metric_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('calculated_value', sa.Float(), nullable=True),
    sa.Column('industry_threshold', sa.Float(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('adjusted_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['credit_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_scores_analysis_id'), 'metric_scores', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_metric_scores_id'), 'metric_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_scores_id'), table_name='metric_scores')
    op.drop_index(op.f('ix_metric_scores_analysis_id'), table_name='metric_scores')
    op.drop_table('metric_scores')
    op.drop_index(op.f('ix_extracted_financials_id'), table_name='extracted_financials')
    op.drop_index(op.f('ix_extracted_financials_document_id'), table_name='extracted_financials')
    op.drop_table('extracted_financials')
    op.drop_index(op.f('ix_credit_analyses_id'), table_name='credit_analyses')
    op.drop_index(op.f('ix_credit_analyses_document_id'), table_name='credit_analyses')
    op.drop_table('credit_analyses')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
