"""add_raw_fields

Revision ID: cce4c5cce918
Revises: 7401f23daf39
Create Date: 2026-03-19 22:59:04.501464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce4c5cce918'
down_revision: Union[str, Sequence[str], None] = '7401f23daf39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_financials', sa.Column('raw_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_financials', 'raw_fields')
    # ### end Alembic commands ###
